### ISSUE TITLE
Use unique values for mocked ID scalars

### ISSUE THREAD

**Issue by marxian** [lola-tech/graphql-kimera#64]
## Summary
Currently Kimera mocks ID scalars as a string. Perhaps it is possible to mock them with unique values.

## Motivation
The most obvious use-case this would facilitate is for UIs which use React to render lists o mocked items, where it is common to use an id as a key. React will encounter problems if the key is not unique. Currently users will need to mock the id of a type explicitly to avoid problems.

## Detailed design
I suspect that a default mock for the ID scalar could use a library like https://www.npmjs.com/package/uuid to achieve this.

## Drawbacks
I can't think of a reason not to do this.

**Comment by c10b10** [comment]
Adding different IDs for all types is currently opt in, in the sense that you can do this as a consumer of Kimera in one go by defining a builder for the `ID` type in which you could use the `uuid` package.

The reason for this is because building different IDs into the library by default has performance implications which would be visible with large schemas. We've been here before, and dropping unique ID's is what brought the initial 10x speed bump.

Currently, the process of mocking a specific field [will be memoized by](https://github.com/lola-tech/graphql-kimera/blob/master/packages/graphql-kimera/src/engine.js#L251-L266) computing a single key from the typename and the mock providers used for this specific field. 

This allows aggressive memoization when the engine has to repeatedly mock types that have the same mock specifications (ie. the same mock providers).

Doing this without breaking memoization is a delicate procedure. I guess the best place to avoid breaking memoization would be [after the field is mocked](https://github.com/lola-tech/graphql-kimera/blob/master/packages/graphql-kimera/src/engine.js#L88-L93), but you would still have to check: 
- if it's an object type or a list of object types, and if they have the id field defined in the schema
- wether the id wasn't already mocked with a mock provider
- additionally, something like this would need to be done for the `buildMocks` function that gets passed as the second argument for [query resolver factory](https://github.com/lola-tech/graphql-kimera/blob/master/packages/graphql-kimera/src/engine.js#L103-L109)

These changes, while not equivalent to breaking memoization, would still require creating at least the double amount of objects, which might be undesirable when we're using kimera for unit testing in React.

I'm not sure the effort is worth it since this can be achieved by a single `ID` builder.
